//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwkTurtleCounter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Turtle : global::System.Configuration.ApplicationSettingsBase {
        
        private static Turtle defaultInstance = ((Turtle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Turtle())));
        
        public static Turtle Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JerichoTurtle {
            get {
                return ((int)(this["JerichoTurtle"]));
            }
            set {
                this["JerichoTurtle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HelenTurtle {
            get {
                return ((int)(this["HelenTurtle"]));
            }
            set {
                this["HelenTurtle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JerichoCookie {
            get {
                return ((int)(this["JerichoCookie"]));
            }
            set {
                this["JerichoCookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HelenCookie {
            get {
                return ((int)(this["HelenCookie"]));
            }
            set {
                this["HelenCookie"] = value;
            }
        }
    }
}
